// Copies ../shared/abi/*.json into src/abi/*.ts as `as const` exports (typed for viem/wagmi).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, "..", "..", "shared", "abi");
const out = path.resolve(here, "..", "src", "abi");
fs.mkdirSync(out, { recursive: true });

const names = [];
for (const file of fs.readdirSync(src).filter((f) => f.endsWith(".json"))) {
  const name = path.basename(file, ".json");
  const raw = JSON.parse(fs.readFileSync(path.join(src, file), "utf8"));
  const abi = Array.isArray(raw) ? raw : raw.abi;
  const body = `// Generated from shared/abi/${file} by scripts/gen-abi.mjs. Do not edit.\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  fs.writeFileSync(path.join(out, `${name}.ts`), body);
  names.push(name);
}
fs.writeFileSync(
  path.join(out, "index.ts"),
  `// Generated by scripts/gen-abi.mjs. Do not edit.\n${names.map((n) => `export { ${n}Abi } from "./${n}";`).join("\n")}\n`
);
console.log("abi:", names.join(", "));
