"""90 - Assemble report/index.html: every chart with its caption, links to every results file, and the markdown conclusions rendered inline."""
import os, sys, glob, html, json, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REP = os.path.join(ROOT, "report"); os.makedirs(REP, exist_ok=True)
CH = os.path.join(ROOT, "charts"); RES = os.path.join(ROOT, "results")

SECTIONS = [("10", "Universe statistics: how fat is the weekend tail?"), ("21", "Pricing versions v1-v4, out of sample"),
            ("30", "Famous weekends"), ("40", "Hermee, the Sleeper"), ("50", "Kip, the Keeper"), ("60", "What the token does while the NYSE is shut"), ("70", "Principal-protection structures")]
def md_to_html(md):
    out = []; in_table = False
    for line in md.splitlines():
        if line.startswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if set("".join(cells)) <= set("-: "): continue
            tag = "th" if not in_table else "td"
            if not in_table: out.append("<table>"); in_table = True
            out.append("<tr>" + "".join(f"<{tag}>{html.escape(c)}</{tag}>" for c in cells) + "</tr>"); continue
        if in_table: out.append("</table>"); in_table = False
        if line.startswith("### "): out.append(f"<h4>{html.escape(line[4:])}</h4>")
        elif line.startswith("## "): out.append(f"<h3>{html.escape(line[3:])}</h3>")
        elif line.startswith("# "): out.append(f"<h2>{html.escape(line[2:])}</h2>")
        elif line.startswith("- "): out.append(f"<li>{inline(line[2:])}</li>")
        elif line.strip(): out.append(f"<p>{inline(line)}</p>")
    if in_table: out.append("</table>")
    return "\n".join(out)
def inline(t):
    t = html.escape(t); t = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", t); t = re.sub(r"`(.+?)`", r"<code>\1</code>", t); return t

parts = ["""<!doctype html><html><head><meta charset="utf-8"><title>afterhours.fi backtest v2</title>
<style>body{font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;max-width:1180px;margin:24px auto;padding:0 16px;color:#0b0b0b;background:#fcfcfb;line-height:1.45}
h1{font-size:26px}h2{font-size:20px;margin-top:40px;border-bottom:1px solid #e6e5e1;padding-bottom:6px}h3{font-size:16px;margin-top:26px}
img{max-width:100%;border:1px solid #e6e5e1;border-radius:6px;margin:8px 0}table{border-collapse:collapse;font-size:12.5px;margin:10px 0;display:block;overflow-x:auto}
td,th{border:1px solid #e6e5e1;padding:4px 8px;text-align:right}th{background:#f3f2ee}td:first-child,th:first-child{text-align:left}
code{background:#f3f2ee;padding:1px 4px;border-radius:3px}.files a{display:inline-block;margin:2px 8px 2px 0;font-size:13px}nav a{margin-right:14px}</style></head><body>
<h1>afterhours.fi - weekend closed-session risk, backtest v2</h1>
<p>Generated by <code>scripts/90_report.py</code>. Every number here is reproducible with <code>run_all.ps1</code>. Read <b>CONCLUSIONS.md</b> and <b>RISK_MEMO.md</b> first.</p>
<nav>""" + " ".join(f'<a href="#s{k}">{html.escape(t)}</a>' for k, t in SECTIONS) + '<a href="#conclusions">Conclusions</a><a href="#risk">Risk memo</a></nav>']
for k, title in SECTIONS:
    parts.append(f'<h2 id="s{k}">{html.escape(title)}</h2>')
    for fp in sorted(glob.glob(os.path.join(CH, f"{k}_*.png"))):
        rel = os.path.relpath(fp, REP).replace("\\", "/"); parts.append(f'<h3>{html.escape(os.path.basename(fp))}</h3><img src="{rel}" loading="lazy">')
    files = sorted(glob.glob(os.path.join(RES, f"{k}_*")))
    parts.append('<div class="files">' + " ".join(f'<a href="{os.path.relpath(f, REP).replace(chr(92), "/")}">{html.escape(os.path.basename(f))}</a>' for f in files if not f.endswith(".log")) + "</div>")
    for mdf in [f for f in files if f.endswith(".md")]:
        parts.append(md_to_html(open(mdf, encoding="utf-8").read()))
for anchor, name in (("conclusions", "CONCLUSIONS.md"), ("risk", "RISK_MEMO.md"), ("versions", "VERSIONS.md"), ("market", "MARKET_RESEARCH.md"), ("strategy", "PRODUCT_STRATEGY.md"), ("lit", "LITERATURE.md")):
    fp = os.path.join(ROOT, name)
    if os.path.exists(fp): parts.append(f'<h2 id="{anchor}">{name}</h2>' + md_to_html(open(fp, encoding="utf-8").read()))
parts.append('<h2 id="research">Research pack</h2><div class="files">' + " ".join(f'<a href="{os.path.relpath(f, REP).replace(chr(92), "/")}">{html.escape(os.path.basename(f))}</a>' for f in sorted(glob.glob(os.path.join(ROOT, "research", "*.md")))) + "</div>")
parts.append("</body></html>")
open(os.path.join(REP, "index.html"), "w", encoding="utf-8").write("\n".join(parts))
print("report ->", os.path.relpath(os.path.join(REP, "index.html"), ROOT))
