// GENERATED by scripts/gen-deployments.mjs from src/deployments/*.json (written by contracts/scripts/deploy.ts). Do not edit.
import type { Deployment } from "../lib/types";
import d0 from "./bscTestnet.json";
import d1 from "./sepolia.json";

export const deployments: Record<number, Deployment> = {
  97: d0 as unknown as Deployment,
  11155111: d1 as unknown as Deployment,
};
