// GENERATED by scripts/gen-deployments.mjs from src/deployments/*.json (written by contracts/scripts/deploy.ts). Do not edit.
import type { Deployment } from "../lib/types";
import d0 from "./sepolia.json";

export const deployments: Record<number, Deployment> = {
  11155111: d0 as unknown as Deployment,
};
