// Copies ../shared/abi/*.json into src/abi/<Name>.ts as `as const` arrays so viem can infer types
// and the build is self-contained (dist/ does not depend on ../shared at runtime).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, "..", "..", "shared", "abi");
const dst = path.resolve(here, "..", "src", "abi");
fs.mkdirSync(dst, { recursive: true });

if (!fs.existsSync(src)) {
  const existing = fs.readdirSync(dst).filter((f) => f.endsWith(".ts") && f !== "index.ts");
  if (existing.length === 0) {
    console.error(`copy-abi: ${src} not found and src/abi is empty`);
    process.exit(1);
  }
  console.log(`copy-abi: ${src} not found, keeping existing ${existing.length} ABI file(s)`);
  process.exit(0);
}

const names = [];
for (const f of fs.readdirSync(src).filter((f) => f.endsWith(".json")).sort()) {
  const name = path.basename(f, ".json");
  const raw = JSON.parse(fs.readFileSync(path.join(src, f), "utf8"));
  const abi = Array.isArray(raw) ? raw : raw.abi;
  if (!Array.isArray(abi)) throw new Error(`copy-abi: ${f} has no abi array`);
  const body = `// generated by scripts/copy-abi.mjs from shared/abi/${f}; do not edit\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  fs.writeFileSync(path.join(dst, `${name}.ts`), body);
  names.push(name);
}
fs.writeFileSync(
  path.join(dst, "index.ts"),
  `// generated by scripts/copy-abi.mjs; do not edit\n${names.map((n) => `export { ${n}Abi } from "./${n}";`).join("\n")}\n`,
);
console.log(`copy-abi: wrote ${names.length} ABI module(s) to src/abi`);
